version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: new_employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
    ports:
      - "5425:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - asset_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
    container_name: backend_service
    ports:
      - "3425:3425"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin234
      - DB_NAME=new_employee_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - asset_network

  frontend:
    build:
      context: ./Frontend
    container_name: frontend_service
    ports:
      - "8047:80"
    networks:
      - asset_network

  hr_page:
    build:
      context: ./Hr_Page
    container_name: hrpage_service
    ports:
      - "8048:80"
    networks:
      - asset_network

volumes:
  pgdata:

networks:
  asset_network:
    driver: bridge
